DEV_DB_NAME: moe_ecommerce_development
DEV_DB_USER: moe
DEV_DB_PASSWORD: password

TEST_DB_NAME: moe_ecommerce_test
TEST_DB_USER: moe
TEST_DB_PASSWORD: password

PRODUCTION_DB_NAME: moe_ecommerce_production
PRODUCTION_DB_USER: moe
PRODUCTION_DB_PASSWORD: password